# Site settings
name: bluebird
description: Bluebird is a fully featured JavaScript promises library with unmatched performance.
url: http://petkaantonov.github.io
baseurl: "/bluebird/web"
title: bluebird
timezone: Helsinki/Finland
highlighter: pygments
exclude:
- Gemfile
- Gemfile.lock
- helpers.rb
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: page
# Build settings
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
version: 2.9.3
gems:
- jekyll-redirect-from
destination: "../gh-pages/web/"
safe: false
encoding: utf-8
host: "0.0.0.0"
